### ISSUE TITLE
ERROR I DONT KNOW WHY I JUST FOLLOW HOW TO INSTALL THIS ONE 

### ISSUE THREAD

**Issue by bojie12345** [YeahItsHayden/hayden_storerob#4]
![image](https://user-images.githubusercontent.com/41977965/133704436-ebe6d609-f873-495e-b4f7-dec6d5622e5f.png)

**Comment by TheCorruptCode** [comment]
Hey, I believe I answered you elsewhere.

Ensure your config settings are set so Max is higher then Min payout.
